#id:NXQ_00202
#title:Proteins with from 2 to 4 transmembrane regions
#tags:region,domain,transmembrane
#acs:
#count: 1055
select distinct ?entry where{
 ?entry :isoform ?iso.
   ?iso :topology ?statement .
   ?statement a :TransmembraneRegion.
}
GROUP BY ?entry ?iso 
HAVING(count( ?statement)>=2 && count( ?statement)<=4)

