#title:Q003 with 37 transmembrane regions or more
#acs:Q9H5I5
#tags:region
#count:1
select distinct ?entry where{
 ?entry :isoform ?iso.
   ?iso :topology ?statement .
   ?statement a :TransmembraneRegion.
}
GROUP BY ?entry ?iso 
HAVING(count( ?statement)>=37)
