#id:NXQ_00003
#title:Proteins with 7 transmembrane regions
#tags:region,domain,transmembrane,topology
#acs:
#count:1026

select distinct ?entry where {
 ?entry :isoform ?iso.
   ?iso :topology ?statement .
   ?statement a :TransmembraneRegion.
}
GROUP BY ?entry ?iso 
HAVING(count( ?statement)=7)
