#title:Proteins highly expressed in brain but not expressed in testis
#acs: A5YM72,P43699,P78411
#tags:expression
#count: 49
#time: 0.4
SELECT distinct ?entry WHERE {
  ?entry :isoform ?iso.
# get all expression
  ?iso :expression ?e1.
# highly expressed in brain
  ?e1 :term/:childOf  cv:TS-0095;:evidence/:expressionLevel :High.

# not expressed in testis
  ?iso :undetectedExpression ?e2.
  ?e2 :term  cv:TS-1030.
  FILTER NOT EXISTS{ ?iso :detectedExpression / :term / :childOf cv:TS-1030}
}
