#title:Proteins whose genes are less than 50000 bp away from the location of the gene coding for protein p53
#tags:gene
#acs:P04278,P04637,P14415,Q15768,Q96F10,Q9BUR4
#count:5

select distinct ?entry where {
   entry:NX_P04637 :gene /:begin ?s;:gene/:chromosome ?chr.
   ?entry :gene/:begin  ?gs;:gene/:chromosome ?chr.
   FILTER( ?gs > (?s -50000) && ?gs <= (?s +50000) && ?entry != entry:NX_P04637)
}
