#title:Proteins that are expressed in liver and involved in transport
#comment:By using "related" for the CV term KW-0813 (keyword 'Transport') we also search using the GO biological process term GO_0006810.
#acs: Q9UPT5, A5D8V6, O15439
#tags:expression,function
#count:1517
#time: 9.7
SELECT distinct ?entry WHERE {
  ?entry :isoform ?iso .
  ?iso :detectedExpression/:term/:childOf cv:TS-0564.
  cv:KW-0813 :related  ?tra .
  ?iso :generalAnnotation / :term ?tra.
}
