#title: Q012 that interact with protein Y and that are involved in splicing
#tags:interaction
#acs:O43143,O75533,Q13573,Q15428,Q15637,Q8IWZ8,Q99459,Q9P013
#count:8
select distinct ?entry WHERE  {
  entry:NX_Q96I25 :isoform / :interaction / :with ?entry.
  ?entry :isoform / :keyword / :in term:KW-0508
}
