#title:Q015 Proteins with a PDZ domain that interact with at least 1 protein which is expressed in brain
#acs:O00151,O00233,O00560,O14640,O14641,O14745,O14907,O14908,O14910,O14936
#tags:selected,region,interaction
#count:128
SELECT distinct ?entry WHERE {
?entry :isoform ?iso.
?iso :region / :term cv:DO-00477. #PDZ domain
?iso :binaryInteraction/:interactant/:isoform?/:detectedExpression/:term/:childOf cv:TS-0095 #brain
}
