#title:Q016 with a mature chain <= 1000 amino acids which are secreted and do not contain cysteines in the mature chain
#acs:P10163,P01258,P01270
tags:sequence
#count:165
#time:0.08
SELECT distinct ?entry  WHERE  {
?entry :isoform ?iso .
?iso :location/:term term:SL-0243;:sequence / :chain ?seq. #secreted
?iso :matureProtein [ :start ?mstart ; :end ?mend]
FILTER ((?mend-?mstart > 0) && (?mend-?mstart <= 1000))	 
BIND(?mend - ?mstart as ?mlen)	 
BIND(substr(?seq, ?mstart, ?mlen) as ?mseq)	 
filter(!regex (?mseq,'C'))
}
