#title:Q017 Proteins >=1000 amino acids and located in nucleus and expression in nervous system
#tags:expression,location,sequence
#acs:A3KN83,A4D0V7,A5PL33,A6NHR9,A8MQ14,B1AJZ9,O00159,O00203,O00267,O00268
#count:927
#pending
#time:1.159
SELECT distinct ?entry WHERE  {
  ?entry :isoform ?iso.
  ?iso :location/:term/:childOf cv:SL-0191.
  ?iso :detectedExpression/:term/:childOf cv:TS-1313.
  ?iso :sequence/:length ?len.
  FILTER (?len>1000)
}
