#title:Proteins with at least 1 HPA antibody that are located in the peroxisome
#acs:O14678
#tags:antibody,subcellular location,cellular component
#count:112
#time:0.572
select  distinct ?entry  where {
 ?entry :isoform ?iso . 
  
  ?iso :mapping ?map . 
  ?map a :AntibodyMapping; :reference / :provenance db:HPA
                 
  {?iso :keyword / :term cv:KW-0576 .}
  UNION 
  {?iso :subcellularLocation / :term /:childOf cv:SL-0204. } 
  UNION 
  {?iso :goCellularComponent / :term /:childOf cv:GO_0005777.}  
}
