#title: Q038 with >=1 selenocysteine in their sequence
#acs:O60613, Q99611, Q9NZV6, ...
#tags:selenocysteine
#count:26
#time:0.1
SELECT distinct ?entry WHERE  {
  #?entry :isoform/:selenocysteine/:in ?statement.
  ?entry :isoform/ :keyword / :in term:KW-0712. # selenocysteine
}