#title:Proteins with at least one selenocysteine in their sequence
#tags:selenocysteine
#acs:O60613, Q99611, Q9NZV6, ...
#count:26
#time:0.1

select distinct ?entry where {
  #?entry :isoform/:selenocysteine/:term ?statement.
  ?entry :isoform/ :keyword / :term cv:KW-0712. # selenocysteine
}
