#title:Q039 with >=1 mutagenesis in a position that correspond to an annotated active site
#acs:P53816, P14550, P15374, ...
#tags:mutagenesis,site
#count:369
#time:0.1
SELECT distinct ?entry WHERE  {
  #?entry :classifiedWith/rdf:type :EnzymeClassificationCv;:isoform ?iso.
  ?entry :isoform ?iso.
  ?iso :mutagenesis /:start ?mutaPos.
  ?iso :activeSite /:start ?actsitePos.
  FILTER(?mutaPos=?actsitePos)
}