#title:Q043  that bind zinc and are not oxidoreductase and not involved in transcription
#acs:Q9Y6I4, A6NIR3, A7E2V4, ...
#tags:zinc,function
#count:1297
#time:0.45
SELECT distinct ?entry WHERE {
 ?entry :isoform ?iso .
 ?iso :keyword / :term term:KW-0479. # metal-binding
 ?iso :keyword / :term term:KW-0862. # zinc
FILTER NOT EXISTS { ?iso :keyword / :term term:KW-0804} # transcription
FILTER NOT EXISTS {?iso :keyword / :term term:KW-560 } # oxidoreductase
}

