#title:Proteins involved in the Reactome pathway xxxx
#tags:pathway
#acs:Q32NB8, O14832, O76050, ...
#count:762
#time:4.6

select distinct ?entry where {
  ?entry :isoform / :function / a :Pathway .
  ?entry  :reference / :provenance db:Reactome .
}
