#title:Q053   which are involved in cell adhesion according to GO with an evidence not IAE and not ISS
#acs: O14788, P07911, Q14393, ...
#tags:function,evidence
#count:515
#time: 0.48
SELECT distinct ?entry WHERE {
 ?entry  :isoform/:function ?statement.
 ?statement :in / :childOf term:GO_0007155.
 ?statement :evidence/:code ?ecode .
  FILTER  ( ?ecode != :IEA && ?ecode != :ISS)
}
