#title:Proteins which are involved in cell adhesion according to GO with an evidence not IAE and not ISS
#tags:function,evidence
#acs: O14788, P07911, Q14393, ...
#count:515
#time: 0.48

select distinct ?entry where {
  ?entry  :isoform/:function ?statement.
  ?statement :term / :childOf cv:GO_0007155.
  ?statement :evidence/:code ?ecode .
   FILTER  ( ?ecode != :IEA && ?ecode != :ISS)
}
