#title:Proteins which are located on the genome next to a protein which is involved in spermatogenesis
#tags:TODO,gene location,function
#acs: , , , ...
#count:
#time: 

select distinct ?entry where {
  ?entry :isoform ?iso.
}

