#title:Proteins which have one or more negatively charged residue in a transmembrane domain
#tags:domain,region,transmembrane,sequence,
#acs: A6NGA9, O14678, ,A8MWL7 ...
#count:2532
#time: 0.58

select distinct ?entry where {
 ?entry :isoform ?iso .
 ?iso :transmembraneRegion  ?tm.
 ?tm :start ?tmstart ; :end ?tmend.
 ?iso :sequence /:chain ?chain.
  BIND (substr(?chain, ?tmstart, ?tmend-?tmstart) as ?tmseq)
  FILTER(regex(?tmseq, '[DE]'))

}
