#title:Q062 which have >=1 zinc finger of any subtype
#acs: Q9Y5X4, Q9Y6I4, Q14527, ...
#tags:domain,zinc-finger
#count:1803
#time: 0.26
SELECT distinct ?entry WHERE {
?entry :isoform ?iso .
?iso :zincFingerRegion ?_.
}

