#title:Q063 which have >=1 RRM RNA-binding domain and either no GO "RNA binding" or a GO "RNA binding" with evidence IEA or ISS
#acs: Q14103, Q6ZRY4, Q8TC92, ...
#tags:RNA-binding,domain,evidence
#count:78
#time: 0.1
SELECT distinct ?entry  WHERE {
 ?entry :isoform ?iso
 {
#>=1 RRM RNA-binding domain
  ?iso :region/:in term:DO-00581.

#GO "RNA binding" with evidence IEA or ISS
  FILTER NOT EXISTS {
   ?iso :function/:in /:childOf term:GO_0003723
  }
 }UNION{
#>=1 RRM RNA-binding domain
  ?iso :region/:in term:DO-00581.

#GO "RNA binding" with evidence IEA or ISS
  ?iso :function ?s1.
  ?s1 :in /:childOf term:GO_0003723;:evidence/:code ?type.
  values ?type {:IEA :ISS}

 }
}

