#title:Q066  that are cytoplasmic with alternate O-glycosylation or phosphorylation at the same positions
#acs: P08047, P31749, P10636, ...
#tags:location,PTM,sequence
#count:17
#time: 0.9
select  distinct ?entry where {
 ?entry :isoform ?iso .
 ?iso :location/:term/:childOf cv:SL-0086.
 ?iso :modifiedResidue /:term ?ptmtype.
 ?iso :modifiedResidue /:start ?ptmpos.
 FILTER (?ptmtype in (cv:PTM-0253, cv:PTM-0254, cv:PTM-0255))  
?iso :glycosylationSite /:start ?ptmpos.
}
