#title: Q067 with alternative acetylation or Ubl conjugation (SUMO or Ubiquitin) at the same positions
#acs: O00154, P14618, Q04206, ...
#tags: location evidence
#count: 740
#time: 0.4
 SELECT  distinct ?entry  WHERE  {
  ?entry :isoform ?iso.
    ?iso :crossLink /:start ?ptmpos.
    ?iso :modifiedResidue ?ptm .
    ?ptm :start ?ptmpos.
    ?ptm rdfs:comment ?comment.
# use this filter to select acetylations
  FILTER regex(?comment, "acetyl","i")
}

