#title: Q068  with protein evidence PE=2 (transcript level)
#acs: A6BM72, A6NEM1, A6NFU8, ...
#tags: protein existence, PE
#count: 2650
#time: 0.45
SELECT distinct ?entry  WHERE  {
  ?entry :existence :Evidence_at_transcript_level
}


