#title:Q070 secreted but without a signal sequence
#acs:P00739,Q14393,P01344,...
#tags:location,signal
#count:396
#time: 0.12
select distinct ?entry where {
  ?entry :isoform ?iso.
    ?iso :location/:term/:childOf cv:SL-0243
 FILTER NOT EXISTS {?iso :signalPeptide ?_}
 }
