#title:Q073 with no domain
#acs: P38405, Q8N5D0, Q9Y6J6, ...
#tags:domain
#count:12249
#time: 2.4
select distinct ?entry where{
  ?entry a :Entry .
  FILTER NOT EXISTS { ?entry :isoform / :region/rdf:type :Domain}
}

