#title:Q076  which are located in mitochondrion and have >=1 HPA antibody and exist in >=1 proteome identification sets
#acs:  A8K5M9, O75570, P23443, ...
#tags:location,antibody,dataset,bug?
#count:1169
#time: 0.4
select  distinct ?entry where {
 ?entry :isoform ?iso .
 ?iso :cellularComponent/:term/:childOf cv:SL-0173.
  ?iso :mapping ?map1.
 ?map1 a :AntibodyMapping.
  ?iso :mapping ?map2.
 ?map2 a :PeptideMapping.
 # the nb is the same if I dont filter on PeptideMapping
}
