#title:Q083 whose genes are on chromosome n that are expressed only a single tissue/organ
#acs: , , , ...
#tags:chromosome,expression,todo
#count:
#time: 
SELECT distinct ?entry count(?tiss) WHERE {
  ?entry :gene / :chromosome "18"^^xsd:string .
  ?entry :isoform  ?iso.
  ?iso :expressionProfile /:term ?tiss.
  ?iso :expressionProfile /:term  /:childOf cv:TS-0564. #liver
  # find topmost parent and only count it
}
#GROUP BY ?entry ?iso HAVING(count(?tiss) < 5)
#FILTER(count(?tiss) < 5))
limit 50

