#title:Proteins whose genes are on chromosome 18 that are expressed only in liver
#tags:chromosome,expression,todo
#acs:
#count:
#time: 

Select distinct ?entry count(?tiss) where {
  ?entry :gene / :chromosome "18"^^xsd:string .
  ?entry :isoform  ?iso.
  ?iso :expressionProfile /:term ?tiss.
  ?iso :expressionProfile /:term  /:childOf cv:TS-0564. #liver
  # find topmost parent and only count it
}
#GROUP BY ?entry ?iso HAVING(count(?tiss) < 5)
#FILTER(count(?tiss) < 5))
limit 50

