#title:Q084  whose genes are on chromosome n that are known to be glycosylated or phosphorylated or acetylated (excluding prediction)
#acs: , , , ...
#tags:chromosome,PTM,todo
#count:
#time: 
select distinct ?entry {
  ?entry :gene / :chromosome "18"^^xsd:string .
  ?entry :isoform  ?iso.
  ?iso :glycosylationSite /:withEvidence /:code ?evcode.
  filter (?evcode not in (:IEA))

} 
