#title:Q088 which have orthologs/paralogs in mammals but not in zebrafish
#tags:federated,ortholog
#acs:,,, ...
#count: 3405
#time: 32

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX ensembl: <http://rdf.ebi.ac.uk/resource/ensembl/>
PREFIX ensemblterms: <http://rdf.ebi.ac.uk/terms/ensembl/>

SELECT distinct ?humanGene ?humanLabel WHERE {
  service <http://wwwdev.ebi.ac.uk/rdf/services/ensembl/sparql> {
SELECT DISTINCT ?humanGene ?mouseGene ?zebraGene ?humanLabel  WHERE {
 ?humanGene rdf:type ensemblterms:protein_coding .
  ?humanGene rdfs:label ?humanLabel .
  ?humanGene obo:RO_0002162 <http://identifiers.org/taxonomy/9606> .
 ?humanGene sio:SIO_000558 ?mouseGene .
 ?mouseGene obo:RO_0002162 <http://identifiers.org/taxonomy/10090> .
  OPTIONAL {
   ?humanGene sio:SIO_000558 ?zebraGene .
   ?zebraGene obo:RO_0002162 <http://identifiers.org/taxonomy/7955> .
   }
  }
 }
FILTER(!bound(?zebraGene)).
#bind(substr(?humanGene^^xsd:string,40,15) as ?ensg).
#?entry :reference /:accession ?ensg. 		  
}
