#title:Q092 with a sequence containing "FF_QYD" where "_" (underscore) is any single amino-acid
#tags:sequence
#acs:
#count: 0
#time: 0.6

select distinct ?entry where {
  ?entry rdf:type :Entry .
  ?entry :isoform / :sequence / :chain ?chain .
  filter ( regex(?chain, "FF.QYD") )
}
