#title:Q092 with a sequence containing "FF_QYD" where "_" (underscore) is any single amino-acid
#acs:
#tags:sequence
#count: 0
#time: 0.6
SELECT distinct ?entry WHERE {
  ?entry rdf:type :Entry .
  ?entry :isoform / :sequence / :chain ?chain .
  filter ( regex(?chain, "FF.QYD") )
}