#title: Q093 with a sequence containing "FF*QYD" where "*" (asterisk) is any peptide of any length
#acs: A7KAX9, A5YKK6, O60494
#tags: sequence
#count: 187
#time: 0.8
SELECT distinct ?entry WHERE {
  ?entry :isoform / :sequence / :chain ?chain .
  filter ( regex(?chain, "FF.+QYD") )
}}