#title: Q097 located on chromosome 2 and having known variants on a phosphotyrosine position
#acs:O15259,O75643,Q12866, ...
#tags: chromosome,variant,PTM
#count:10
#time:0.15
select distinct ?entry where {
  ?entry :gene / :chromosome "2"^^xsd:string .
  ?entry :isoform ?iso.
  ?iso :variant /:start ?varpos.
  ?iso :modifiedResidue ?modres.
  ?modres :term cv:PTM-0255.
  ?modres :start ?varpos.
}

