#title: Q099 entries having PTMS that also fall on variants
#ac:Q9UPT9,Q9UPN4,Q9Y272
#tags: PTM,variants 
#count:4492 
#time:18.3  

select distinct ?entry where {
  ?entry :isoform ?iso.
  ?iso :variant /:start ?varpos.
  ?iso :ptm /:start ?varpos.
}
