#title: Q100  expressed in liver having COSMIC variants associated with liver/hepatic cancer
#ac:Q9UPT5,Q9UPT9,Q9UQB8
#tags: variant,disease,expression 
#count:8066
#time:3.4

select distinct ?entry where {
  ?entry :isoform ?iso.
  ?iso :detectedExpression/:term/:childOf cv:TS-0564.
  ?iso :variant /:evidence ?ev.
  ?ev :assignedBy source:Cosmic.
  ?ev :experimentalContext /:tissue term:TS-0564.
}
