#title:Proteins with at least one cross-reference to the ProteinModelPortal but no cross-references to PDB.
#tags:Xref,cross-refences,PDB,3D-structure
#ac:A0A183,A0PJX8,A1L020
#count:14438
#time:3.1

select distinct ?entry where {
  ?entry :reference / :provenance db:ProteinModelPortal .
  filter not exists {
    ?entry :reference / :provenance db:PDB
  }
}
