#title: Q106 All proteins annotated as glycosylated but with no recorded glycosylation site.
#ac:P49765,P11171,P13646
#tags:PTM
#count:83
#time:0.1

select distinct ?entry {
?entry :isoform ?iso .
?iso :keyword / :term cv:KW-0325.
 filter not exists { ?entry :isoform /:glycosylationSite ?_.  }
}