#title: Q107 All proteins with a protein evidence not "At protein level" with a HGNC identifier/xref that includes the regexp "orf"
#ac:A6NJI1,C9JXX5,A1A4V9
#tags:existence.orf
#count:287
#time:0.42

select  distinct ?entry {
  ?entry :existence ?level .
  filter (?level != :Evidence_at_protein_level) .
  ?entry :reference ?r .
  ?r :provenance db:HGNC ; :accession ?ac .
  filter (regex(?ac,'orf')) .
}