#title:Proteins that have a MS-identified peptide that maps partly or fully into a signal sequence
#tags:signal sequence,peptide,mass spectrometry,proteomics
#ac:O43570,P22891,P01023
#count:909
#time:1.3

select distinct ?entry where {
  ?entry :isoform ?iso .
#get Signal position
  ?iso :signalPeptide [:start ?s1;:end ?s2] .
#get peptide position
  ?iso :peptideMapping /:position [ :start ?p1 ; :end ?p2] .
#match positions
  filter ( ?p2 >= ?s1 && ?p1 = ?s2   )
}
