#title:Proteins With one transmembrane domain and no annotated topology
#tags:domain,transmembrane,topology
#ac:A0A5B9,A0AVI2,A1L0T0
#count:682
#time:0.12

select distinct ?entry where {
 ?entry :isoform ?iso
 { select ?iso where
                  { 
                        ?iso :transmembraneRegion ?tm. 
            OPTIONAL { ?iso :topologicalDomain ?topo. }
            FILTER (!bound(?topo)) .	
                  }
 GROUP BY ?iso HAVING(count( ?tm)=1)
 }
}
order by ?entry
