package org.nextprot.api.core.utils.annot.export;

public enum Header {
    ENTRY_ACCESSION,
    TERM_ACCESSION,
    TERM_NAME,
    ANNOTATION_QUALITY,
    ECO_ACCESSION,
    ECO_NAME,
    EVIDENCE_ASSIGNED_BY,
    EVIDENCE_QUALITY,
    EXPRESSION_LEVEL,
    STAGE_ACCESSION,
    STAGE_NAME,
    CELL_LINE_ACCESSION,
    CELL_LINE_NAME,
    DISEASE_ACCESSION,
    DISEASE_NAME,
    ORGANELLE_ACCESSION,
    ORGANELLE_NAME,
}
